@echo off
setlocal ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION

set "ROOTDIR=%~dp0"

set CONFIGURATION=%1
set PLATFORM=%2
set BUILD_CONFIG=!CONFIGURATION!
set PLATFORM_TARGET=!PLATFORM!

if "!CONFIGURATION!"=="ReleaseMT" (
	set BUILD_CONFIG=Release
)

if "%PLATFORM%"=="x64" (
set "TOOL_SET=Visual Studio 17 2022"
set "PLATFORM_NAME=x64"
) else (
set "TOOL_SET=Visual Studio 17 2022" 
set "PLATFORM_NAME=Win32"
)

if "!CONFIGURATION!"=="ReleaseMT" (
set "RT=/MT" 
) else (
set "RT=/MD"
)

set "CMAKE_C_FLAGS_DEBUG=!RT!d /Zi /Od /Ob0 /RTC1 /D_DEBUG"
set "CMAKE_C_FLAGS_MINSIZEREL=!RT! /O1 /Ob1 /DNDEBUG"
set "CMAKE_C_FLAGS_RELEASE=!RT!  /O2 /Ob2 /DNDEBUG"
set "CMAKE_C_FLAGS_RELWITHDEBINFO=!RT! /Zi /O2 /Ob1 /DNDEBUG"

set "CMAKE_INSTALL_PREFIX=!ROOTDIR!..\3rdparty"
set "CMAKE_INSTALL_LIBDIR=!ROOTDIR!..\3rdparty\lib\!PLATFORM!\!CONFIGURATION!"
set "CMAKE_INSTALL_BINDIR=!ROOTDIR!..\3rdparty\bin\!PLATFORM!\!CONFIGURATION!"
set "CMAKE_INSTALL_INCLUDEDIR=!ROOTDIR!..\3rdparty\include"


set "BUILDDIR=!ROOTDIR!..\3rdparty\lzo\build\!PLATFORM!"

if not exist "!BUILDDIR!" mkdir "!BUILDDIR!"

cd "!BUILDDIR!"
if errorlevel 1 exit /B 1


cmake -G "!TOOL_SET!" ^
-A "!PLATFORM_NAME!" ^
-DENABLE_SHARED="ON" ^
-DENABLE_STATIC="ON" ^
-DCMAKE_POLICY_VERSION_MINIMUM="3.5" ^
-DCMAKE_INSTALL_PREFIX="!CMAKE_INSTALL_PREFIX!" ^
-DCMAKE_INSTALL_LIBDIR="!CMAKE_INSTALL_LIBDIR!" ^
-DCMAKE_INSTALL_BINDIR="!CMAKE_INSTALL_BINDIR!" ^
-DCMAKE_INSTALL_INCLUDEDIR="!CMAKE_INSTALL_INCLUDEDIR!" ^
-DCMAKE_C_FLAGS_DEBUG="!CMAKE_C_FLAGS_DEBUG!" ^
-DCMAKE_C_FLAGS_MINSIZEREL="!CMAKE_C_FLAGS_MINSIZEREL!" ^
-DCMAKE_C_FLAGS_RELEASE="!CMAKE_C_FLAGS_RELEASE!" ^
-DCMAKE_C_FLAGS_RELWITHDEBINFO="!CMAKE_C_FLAGS_RELWITHDEBINFO!" ^
"!ROOTDIR!..\3rdparty\lzo"

if errorlevel 1  exit /B 4

cmake --build . --config !BUILD_CONFIG! --target INSTALL -- /maxcpucount:4
if errorlevel 1  exit /B 4

goto :END

:END
endlocal
